// OpenCode agent bridge: generates and keeps in sync an opencode.json
// provider block and .opencode/agent/*.md subagents that target the phone
// cluster's virtual models (auto, pool/<name>, node/<alias>). See the
// gateway's virtual-model contract for "kind", pools and node aliases.
package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/dzaczek/phoneborg/controller/gateway"
)

const (
	ocProviderDefault    = "phoneborg"
	ocAgentDirName       = ".opencode/agent"
	ocManifestPath       = ".opencode/phoneborg-managed.json"
	ocGeneratedMarker    = "<!-- generated by pbctl opencode; edit the template via pbctl, local edits are overwritten -->"
	ocFastPoolName       = "fast"
	ocFastPoolDesc       = "Fast tool-less workers on any phone"
	ocOutputLimit        = 2048
	ocDefaultCtx         = 16384
	ocReadToolsNoteWords = "read-tools adds read, grep and glob to every managed agent (~1k extra prompt tokens per call)"
)

func opencodeCmd(c *client, o *out, rest []string) error {
	if len(rest) == 0 {
		return errUsage
	}
	sub, args := rest[0], rest[1:]
	switch sub {
	case "init":
		return opencodeInit(c, o, args)
	case "sync":
		return opencodeSync(c, o, args)
	case "watch":
		return opencodeWatch(c, o, args)
	case "status":
		return opencodeStatus(c, o, args)
	case "prewarm":
		return opencodePrewarm(c, o, args)
	}
	return errUsage
}

// ---- wire types (the admin API these talk to is landing in parallel; keep
// these local instead of importing half-built controller types) ----

// ocPool mirrors the pool contract (GET/PUT /admin/pools).
type ocPool struct {
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	Models      []string `json:"models,omitempty"`
	Nodes       []string `json:"nodes,omitempty"`
	Classes     []string `json:"classes,omitempty"`
	MinGenTPS   float64  `json:"min_gen_tps,omitempty"`
	Routing     string   `json:"routing,omitempty"`
}

type ocPoolList struct {
	Pools []ocPool `json:"pools"`
}

// ocAdminNode is the slice of GET /admin/nodes this command needs: id, alias
// (once the alias PATCH lands), device and served model/context.
type ocAdminNode struct {
	ID        string `json:"id"`
	Alias     string `json:"alias"`
	Inventory struct {
		Manufacturer string `json:"manufacturer"`
		Model        string `json:"model"`
	} `json:"inventory"`
	LastHeartbeat *struct {
		Runtime *struct {
			Model   string `json:"model"`
			Ready   bool   `json:"ready"`
			CtxSize int    `json:"ctx_size"`
		} `json:"runtime"`
	} `json:"last_heartbeat"`
}

func (n ocAdminNode) device() string {
	return strings.TrimSpace(n.Inventory.Manufacturer + " " + n.Inventory.Model)
}

func (n ocAdminNode) servedModel() string {
	if n.LastHeartbeat != nil && n.LastHeartbeat.Runtime != nil {
		return n.LastHeartbeat.Runtime.Model
	}
	return ""
}

func (n ocAdminNode) ctxSize() int {
	if n.LastHeartbeat != nil && n.LastHeartbeat.Runtime != nil {
		return n.LastHeartbeat.Runtime.CtxSize
	}
	return 0
}

// ocModel is one GET /v1/models entry: a real served model, or a virtual
// "auto" | "pool/<name>" | "node/<alias>" entry with "kind" set.
type ocModel struct {
	ID          string `json:"id"`
	Object      string `json:"object"`
	OwnedBy     string `json:"owned_by"`
	Kind        string `json:"kind"`
	Nodes       int    `json:"nodes"`
	Description string `json:"description,omitempty"`
	Model       string `json:"model,omitempty"`
	Ready       bool   `json:"ready,omitempty"`
}

// kindOrDefault treats a missing "kind" (a controller that predates the
// virtual-model work) as a real served model.
func (m ocModel) kindOrDefault() string {
	if m.Kind == "" {
		return "model"
	}
	return m.Kind
}

type ocPrewarmRequest struct {
	Target   string          `json:"target"`
	Messages []ocChatMessage `json:"messages"`
}

type ocChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type ocPrewarmNodeResult struct {
	NodeID string `json:"node_id"`
	Alias  string `json:"alias"`
	OK     bool   `json:"ok"`
	MS     int    `json:"ms"`
	Error  string `json:"error"`
}

type ocPrewarmResponse struct {
	Results []ocPrewarmNodeResult `json:"results"`
}

// clusterState is the cluster-facing input to config/agent generation.
type clusterState struct {
	Models []ocModel
	Nodes  []ocAdminNode
}

func fetchClusterState(c *client) (clusterState, error) {
	var st clusterState
	modelsRaw, err := c.request(http.MethodGet, "/v1/models", nil, c.apiKey)
	if err != nil {
		return st, err
	}
	var ml struct {
		Data []ocModel `json:"data"`
	}
	if err := json.Unmarshal(modelsRaw, &ml); err != nil {
		return st, err
	}
	st.Models = ml.Data

	nodesRaw, err := c.do(http.MethodGet, "/admin/nodes", nil)
	if err != nil {
		return st, err
	}
	if err := json.Unmarshal(nodesRaw, &st.Nodes); err != nil {
		return st, err
	}
	return st, nil
}

// isHTTP404 recognizes the "HTTP 404: ..." errors client.request formats,
// used to detect an older controller that has no pools/prewarm API yet.
func isHTTP404(err error) bool {
	return err != nil && strings.Contains(err.Error(), "HTTP 404")
}

// aliasedNode is one phone with an alias, as seen through /v1/models
// (node/<alias> entries) and cross-referenced with /admin/nodes for its
// device string.
type aliasedNode struct {
	Alias       string
	NodeID      string
	Device      string
	ServedModel string
	Ready       bool
	NodesReady  int
}

// aliasedNodesFromModels lists every node/<alias> entry in models, filling
// in device info from nodes when the alias matches.
func aliasedNodesFromModels(models []ocModel, nodes []ocAdminNode) []aliasedNode {
	byAlias := map[string]ocAdminNode{}
	for _, n := range nodes {
		if n.Alias != "" {
			byAlias[n.Alias] = n
		}
	}
	var out []aliasedNode
	for _, m := range models {
		if m.kindOrDefault() != "node" {
			continue
		}
		alias := strings.TrimPrefix(m.ID, "node/")
		an := aliasedNode{Alias: alias, ServedModel: m.Model, Ready: m.Ready, NodesReady: m.Nodes}
		if n, ok := byAlias[alias]; ok {
			an.NodeID = n.ID
			an.Device = n.device()
			if an.ServedModel == "" {
				an.ServedModel = n.servedModel()
			}
		}
		out = append(out, an)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Alias < out[j].Alias })
	return out
}

// modelContextLimit is the node ctx if known, else the 16384 default.
func modelContextLimit(m ocModel, nodes []ocAdminNode) int {
	switch m.kindOrDefault() {
	case "node":
		alias := strings.TrimPrefix(m.ID, "node/")
		for _, n := range nodes {
			if n.Alias == alias || n.ID == alias {
				if c := n.ctxSize(); c > 0 {
					return c
				}
			}
		}
	case "model":
		best := 0
		for _, n := range nodes {
			if n.servedModel() == m.ID && n.ctxSize() > best {
				best = n.ctxSize()
			}
		}
		if best > 0 {
			return best
		}
	}
	return ocDefaultCtx
}

func modelDisplayName(m ocModel, nodes []ocAdminNode) string {
	switch m.kindOrDefault() {
	case "auto":
		return "Auto (any ready phone)"
	case "pool":
		if m.Description != "" {
			return m.Description
		}
		return "Pool " + strings.TrimPrefix(m.ID, "pool/")
	case "node":
		alias := strings.TrimPrefix(m.ID, "node/")
		served := m.Model
		if served == "" {
			for _, n := range nodes {
				if n.Alias == alias {
					served = n.servedModel()
				}
			}
		}
		if served == "" {
			served = "no model"
		}
		return fmt.Sprintf("Phone %s (%s)", alias, served)
	default:
		return m.ID
	}
}

// ---- provider block (opencode.json / opencode.jsonc "provider.<id>") ----

type ocLimit struct {
	Context int `json:"context"`
	Output  int `json:"output"`
}

type ocProviderModel struct {
	Name  string  `json:"name"`
	Limit ocLimit `json:"limit"`
}

type ocProviderOptions struct {
	BaseURL       string `json:"baseURL"`
	APIKey        string `json:"apiKey"`
	Timeout       bool   `json:"timeout"`
	HeaderTimeout int    `json:"headerTimeout"`
	ChunkTimeout  int    `json:"chunkTimeout"`
}

type ocProviderBlock struct {
	NPM     string                     `json:"npm"`
	Name    string                     `json:"name"`
	Options ocProviderOptions          `json:"options"`
	Models  map[string]ocProviderModel `json:"models"`
}

type ocProviderWrapper struct {
	Provider map[string]ocProviderBlock `json:"provider"`
}

func buildProviderBlock(baseURL string, models []ocModel, nodes []ocAdminNode) ocProviderBlock {
	pb := ocProviderBlock{
		NPM:  "@ai-sdk/openai-compatible",
		Name: "PhoneBorg",
		Options: ocProviderOptions{
			BaseURL: baseURL, APIKey: "{env:PHONEBORG_API_KEY}",
			Timeout: false, HeaderTimeout: 1800000, ChunkTimeout: 1800000,
		},
		Models: map[string]ocProviderModel{},
	}
	for _, m := range models {
		pb.Models[m.ID] = ocProviderModel{
			Name:  modelDisplayName(m, nodes),
			Limit: ocLimit{Context: modelContextLimit(m, nodes), Output: ocOutputLimit},
		}
	}
	return pb
}

// hasJSONComments reports whether data contains a // or /* */ comment
// outside of a string literal, i.e. it is JSONC, not plain JSON.
func hasJSONComments(data []byte) bool {
	inString, escaped := false, false
	for i := 0; i < len(data); i++ {
		c := data[i]
		if inString {
			switch {
			case escaped:
				escaped = false
			case c == '\\':
				escaped = true
			case c == '"':
				inString = false
			}
			continue
		}
		switch {
		case c == '"':
			inString = true
		case c == '/' && i+1 < len(data) && (data[i+1] == '/' || data[i+1] == '*'):
			return true
		}
	}
	return false
}

func isJSONCConfig(path string, data []byte) bool {
	if strings.EqualFold(filepath.Ext(path), ".jsonc") {
		return true
	}
	return hasJSONComments(data)
}

// plainJSONHasProviderKey reports whether root.provider.<provider> exists in
// a strict-JSON config.
func plainJSONHasProviderKey(data []byte, provider string) (bool, error) {
	var root map[string]json.RawMessage
	if err := json.Unmarshal(data, &root); err != nil {
		return false, err
	}
	raw, ok := root["provider"]
	if !ok {
		return false, nil
	}
	var providers map[string]json.RawMessage
	if err := json.Unmarshal(raw, &providers); err != nil {
		return false, err
	}
	_, ok = providers[provider]
	return ok, nil
}

// mergeProviderBlockJSON sets root.provider.<provider> = block in a strict
// JSON document, leaving every other key (and every other provider) as it
// was. Key order is not preserved (encoding/json sorts map keys), but every
// value is.
func mergeProviderBlockJSON(data []byte, provider string, block ocProviderBlock) ([]byte, error) {
	var root map[string]json.RawMessage
	if err := json.Unmarshal(data, &root); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	if root == nil {
		root = map[string]json.RawMessage{}
	}
	var providers map[string]json.RawMessage
	if raw, ok := root["provider"]; ok {
		if err := json.Unmarshal(raw, &providers); err != nil {
			return nil, fmt.Errorf("parse provider block: %w", err)
		}
	}
	if providers == nil {
		providers = map[string]json.RawMessage{}
	}
	blockRaw, err := json.Marshal(block)
	if err != nil {
		return nil, err
	}
	providers[provider] = blockRaw
	providersRaw, err := json.Marshal(providers)
	if err != nil {
		return nil, err
	}
	root["provider"] = providersRaw
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func backupFile(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return os.WriteFile(path+".bak", data, 0o644)
}

func printProviderBlockToPaste(o *out, provider string, block ocProviderBlock, path string) {
	data, _ := json.MarshalIndent(block, "", "  ")
	fmt.Fprintf(o.w, "%s already configures opencode; paste this under \"provider\":\n\n\"%s\": %s\n\n", path, provider, data)
}

// opencodeWriteConfig implements the init config rules: create a fresh
// opencode.json when neither file exists; merge into an existing plain JSON
// file that lacks the provider (or, with force, replace it); otherwise
// (JSONC, or already configured without force) leave the file untouched and
// print the block to paste. managed is true only when this call created the
// file from scratch.
func opencodeWriteConfig(dir, provider string, block ocProviderBlock, force bool, o *out) (path string, managed bool, err error) {
	jsonPath := filepath.Join(dir, "opencode.json")
	jsoncPath := filepath.Join(dir, "opencode.jsonc")
	jsonExists, jsoncExists := fileExists(jsonPath), fileExists(jsoncPath)

	if !jsonExists && !jsoncExists {
		wrapper := ocProviderWrapper{Provider: map[string]ocProviderBlock{provider: block}}
		data, err := json.MarshalIndent(wrapper, "", "  ")
		if err != nil {
			return "", false, err
		}
		data = append(data, '\n')
		if err := gateway.WriteFileAtomic(jsonPath, data, 0o644); err != nil {
			return "", false, err
		}
		fmt.Fprintf(o.w, "wrote %s\n", jsonPath)
		return jsonPath, true, nil
	}

	path = jsoncPath
	if jsonExists {
		path = jsonPath
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false, err
	}

	if isJSONCConfig(path, data) {
		printProviderBlockToPaste(o, provider, block, path)
		return path, false, nil
	}

	hasProvider, err := plainJSONHasProviderKey(data, provider)
	if err != nil {
		// Malformed despite having no comments: be safe, don't touch it.
		printProviderBlockToPaste(o, provider, block, path)
		return path, false, nil
	}
	if hasProvider && !force {
		printProviderBlockToPaste(o, provider, block, path)
		return path, false, nil
	}

	merged, err := mergeProviderBlockJSON(data, provider, block)
	if err != nil {
		return "", false, err
	}
	if err := backupFile(path); err != nil {
		return "", false, err
	}
	if err := gateway.WriteFileAtomic(path, merged, 0o644); err != nil {
		return "", false, err
	}
	verb := "merged provider block into"
	if hasProvider {
		verb = "replaced provider block in"
	}
	fmt.Fprintf(o.w, "%s %s (backup at %s.bak)\n", verb, path, path)
	return path, false, nil
}

// ---- agent file rendering ----

type ocAgentSpec struct {
	Name        string
	Description string
	Model       string
	ReadTools   bool
	Body        string
}

func renderAgent(spec ocAgentSpec) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "description: %s\n", spec.Description)
	b.WriteString("mode: subagent\n")
	fmt.Fprintf(&b, "model: %s\n", spec.Model)
	b.WriteString("tools:\n")
	b.WriteString("  \"*\": false\n")
	if spec.ReadTools {
		b.WriteString("  read: true\n")
		b.WriteString("  grep: true\n")
		b.WriteString("  glob: true\n")
	}
	b.WriteString("---\n")
	b.WriteString(strings.TrimRight(spec.Body, "\n"))
	b.WriteString("\n\n")
	b.WriteString(ocGeneratedMarker)
	b.WriteString("\n")
	return b.String()
}

// parseAgentFrontmatter extracts the "model:" value and the prompt body (the
// generated-by marker stripped) from a rendered agent file. It is the
// inverse of renderAgent.
func parseAgentFrontmatter(content string) (model, body string, err error) {
	const openFence = "---\n"
	if !strings.HasPrefix(content, openFence) {
		return "", "", errors.New("agent file: missing frontmatter")
	}
	rest := content[len(openFence):]
	idx := strings.Index(rest, "\n---\n")
	if idx < 0 {
		return "", "", errors.New("agent file: unterminated frontmatter")
	}
	for _, line := range strings.Split(rest[:idx], "\n") {
		if v, ok := strings.CutPrefix(line, "model:"); ok {
			model = strings.TrimSpace(v)
		}
	}
	if model == "" {
		return "", "", errors.New("agent file: missing model")
	}
	body = rest[idx+len("\n---\n"):]
	body = strings.TrimSuffix(body, "\n"+ocGeneratedMarker+"\n")
	body = strings.TrimSuffix(body, "\n"+ocGeneratedMarker)
	body = strings.TrimRight(body, "\n")
	return model, body, nil
}

const bodyBorgFast = `You are a fast, tool-less worker on the PhoneBorg phone cluster.

Answer concisely; you get all needed context in the task. Do not ask
follow-up questions or request more information — respond directly from
what is given.`

const bodyBorgSummarize = `You are a summarization worker on the PhoneBorg phone cluster.

Summarize the text given in the task:
- keep the key facts, numbers and decisions; drop filler
- plain prose, no headings, no preamble
- match the requested length if one is given, otherwise 3-5 sentences
- do not add information that is not in the source text`

const bodyBorgReview = `You are a review worker on the PhoneBorg phone cluster.

Review the snippet given in the task. List every issue found as:
- SEVERITY (critical|major|minor|nit): short description

If there are no issues, say so in one line. Do not rewrite the snippet
unless asked.`

func borgFastAgentSpec(provider string, readTools bool) ocAgentSpec {
	return ocAgentSpec{Name: "borg-fast", Description: "Fast tool-less worker on the phone pool (pool/fast).",
		Model: provider + "/pool/fast", ReadTools: readTools, Body: bodyBorgFast}
}

func borgSummarizeAgentSpec(provider string, readTools bool) ocAgentSpec {
	return ocAgentSpec{Name: "borg-summarize", Description: "Summarizes text on the phone pool (pool/fast).",
		Model: provider + "/pool/fast", ReadTools: readTools, Body: bodyBorgSummarize}
}

func borgReviewAgentSpec(provider string, readTools bool) ocAgentSpec {
	return ocAgentSpec{Name: "borg-review", Description: "Reviews a code or text snippet on the phone pool (pool/fast).",
		Model: provider + "/pool/fast", ReadTools: readTools, Body: bodyBorgReview}
}

func phoneAgentSpec(provider string, n aliasedNode, readTools bool) ocAgentSpec {
	device := n.Device
	if device == "" {
		device = "unknown device"
	}
	served := n.ServedModel
	if served == "" {
		served = "no model"
	}
	return ocAgentSpec{
		Name:        "phone-" + n.Alias,
		Description: fmt.Sprintf("worker pinned to phone %s (%s, %s)", n.Alias, device, served),
		Model:       provider + "/node/" + n.Alias,
		ReadTools:   readTools,
		Body:        bodyBorgFast,
	}
}

func managedAgentSpecs(provider string, readTools bool, aliased []aliasedNode) []ocAgentSpec {
	specs := []ocAgentSpec{
		borgFastAgentSpec(provider, readTools),
		borgSummarizeAgentSpec(provider, readTools),
		borgReviewAgentSpec(provider, readTools),
	}
	for _, n := range aliased {
		specs = append(specs, phoneAgentSpec(provider, n, readTools))
	}
	return specs
}

// targetForAgentName maps a managed agent's file name back to its model
// target (without the provider prefix), from the naming convention alone.
func targetForAgentName(name string) string {
	if alias, ok := strings.CutPrefix(name, "phone-"); ok {
		return "node/" + alias
	}
	return "pool/fast"
}

// ---- manifest ----

type ocManifest struct {
	Version       int               `json:"version"`
	Provider      string            `json:"provider"`
	BaseURL       string            `json:"base_url"`
	ReadTools     bool              `json:"read_tools"`
	ConfigPath    string            `json:"config_path,omitempty"`
	ConfigManaged bool              `json:"config_managed"`
	Files         map[string]string `json:"files"`
	UpdatedAt     time.Time         `json:"updated_at"`
}

func (m ocManifest) agentNames() []string {
	prefix := ocAgentDirName + "/"
	var names []string
	for rel := range m.Files {
		if !strings.HasPrefix(rel, prefix) || !strings.HasSuffix(rel, ".md") {
			continue
		}
		names = append(names, strings.TrimSuffix(strings.TrimPrefix(rel, prefix), ".md"))
	}
	sort.Strings(names)
	return names
}

func loadManifest(dir string) (ocManifest, bool, error) {
	data, err := os.ReadFile(filepath.Join(dir, ocManifestPath))
	if errors.Is(err, os.ErrNotExist) {
		return ocManifest{}, false, nil
	}
	if err != nil {
		return ocManifest{}, false, err
	}
	var m ocManifest
	if err := json.Unmarshal(data, &m); err != nil {
		return ocManifest{}, false, err
	}
	if m.Files == nil {
		m.Files = map[string]string{}
	}
	return m, true, nil
}

func (m ocManifest) save(dir string) error {
	path := filepath.Join(dir, ocManifestPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	return gateway.WriteFileAtomic(path, append(data, '\n'), 0o644)
}

func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func relPath(dir, path string) string {
	rel, err := filepath.Rel(dir, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}

// ocSyncResult is a diff summary: which managed files were added, removed,
// regenerated because their template changed, or left as is.
type ocSyncResult struct {
	Added, Removed, Updated, Kept []string
	Warnings                      []string
}

func (r ocSyncResult) changed() bool {
	return len(r.Added) > 0 || len(r.Removed) > 0 || len(r.Updated) > 0
}

func (r ocSyncResult) summary() string {
	return fmt.Sprintf("added %d, removed %d, updated %d, kept %d", len(r.Added), len(r.Removed), len(r.Updated), len(r.Kept))
}

// syncAgentFiles writes every wanted agent spec under dir/.opencode/agent,
// removes managed files that are no longer wanted (unless hand-edited), and
// updates manifest.Files in place. It is idempotent: running it twice with
// the same specs yields an all-kept result.
func syncAgentFiles(dir string, specs []ocAgentSpec, manifest *ocManifest) (ocSyncResult, error) {
	agentDir := filepath.Join(dir, ocAgentDirName)
	if err := os.MkdirAll(agentDir, 0o755); err != nil {
		return ocSyncResult{}, err
	}

	var res ocSyncResult
	wanted := map[string]bool{}
	for _, spec := range specs {
		rel := ocAgentDirName + "/" + spec.Name + ".md"
		wanted[rel] = true
		content := renderAgent(spec)
		hash := sha256Hex([]byte(content))
		full := filepath.Join(dir, rel)
		existingHash, tracked := manifest.Files[rel]

		data, readErr := os.ReadFile(full)
		switch {
		case errors.Is(readErr, os.ErrNotExist):
			if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
				return res, err
			}
			manifest.Files[rel] = hash
			res.Added = append(res.Added, rel)
		case readErr != nil:
			return res, readErr
		case tracked && sha256Hex(data) != existingHash:
			res.Warnings = append(res.Warnings, fmt.Sprintf("%s was edited by hand; left as is", rel))
			res.Kept = append(res.Kept, rel)
		case string(data) == content:
			manifest.Files[rel] = hash
			res.Kept = append(res.Kept, rel)
		default:
			if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
				return res, err
			}
			manifest.Files[rel] = hash
			res.Updated = append(res.Updated, rel)
		}
	}

	prefix := ocAgentDirName + "/"
	for rel, hash := range manifest.Files {
		if !strings.HasPrefix(rel, prefix) || wanted[rel] {
			continue
		}
		full := filepath.Join(dir, rel)
		data, err := os.ReadFile(full)
		if errors.Is(err, os.ErrNotExist) {
			delete(manifest.Files, rel)
			continue
		}
		if err != nil {
			return res, err
		}
		if sha256Hex(data) != hash {
			res.Warnings = append(res.Warnings, fmt.Sprintf("%s was edited by hand; not removing", rel))
			continue
		}
		if err := os.Remove(full); err != nil {
			return res, err
		}
		delete(manifest.Files, rel)
		res.Removed = append(res.Removed, rel)
	}

	sort.Strings(res.Added)
	sort.Strings(res.Removed)
	sort.Strings(res.Updated)
	sort.Strings(res.Kept)
	return res, nil
}

// syncManagedConfig refreshes a managed (init-created) plain-JSON config's
// provider models list, unless it was hand-edited since it was generated.
func syncManagedConfig(dir string, manifest *ocManifest, block ocProviderBlock) (changed bool, warn string, err error) {
	if !manifest.ConfigManaged || manifest.ConfigPath == "" {
		return false, "", nil
	}
	full := filepath.Join(dir, manifest.ConfigPath)
	data, err := os.ReadFile(full)
	if errors.Is(err, os.ErrNotExist) {
		return false, "", nil
	}
	if err != nil {
		return false, "", err
	}
	if h, ok := manifest.Files[manifest.ConfigPath]; ok && sha256Hex(data) != h {
		return false, fmt.Sprintf("%s was edited by hand; not updating its model list", manifest.ConfigPath), nil
	}
	wrapper := ocProviderWrapper{Provider: map[string]ocProviderBlock{manifest.Provider: block}}
	newData, err := json.MarshalIndent(wrapper, "", "  ")
	if err != nil {
		return false, "", err
	}
	newData = append(newData, '\n')
	if string(newData) == string(data) {
		return false, "", nil
	}
	if err := gateway.WriteFileAtomic(full, newData, 0o644); err != nil {
		return false, "", err
	}
	manifest.Files[manifest.ConfigPath] = sha256Hex(newData)
	return true, "", nil
}

// runOpenCodeSync does the work of "pbctl opencode sync" without printing
// anything, so both the sync command and watch's loop can share it.
func runOpenCodeSync(c *client, dir string) (ocSyncResult, error) {
	manifest, ok, err := loadManifest(dir)
	if err != nil {
		return ocSyncResult{}, err
	}
	if !ok {
		return ocSyncResult{}, fmt.Errorf("no %s; run 'pbctl opencode init' first", filepath.Join(dir, ocManifestPath))
	}

	state, err := fetchClusterState(c)
	if err != nil {
		return ocSyncResult{}, err
	}

	aliased := aliasedNodesFromModels(state.Models, state.Nodes)
	specs := managedAgentSpecs(manifest.Provider, manifest.ReadTools, aliased)
	res, err := syncAgentFiles(dir, specs, &manifest)
	if err != nil {
		return res, err
	}

	if manifest.ConfigManaged {
		block := buildProviderBlock(manifest.BaseURL, state.Models, state.Nodes)
		changedCfg, warn, err := syncManagedConfig(dir, &manifest, block)
		if err != nil {
			return res, err
		}
		if warn != "" {
			res.Warnings = append(res.Warnings, warn)
		}
		if changedCfg {
			res.Updated = append(res.Updated, manifest.ConfigPath)
			sort.Strings(res.Updated)
		}
	}

	manifest.UpdatedAt = time.Now().UTC()
	if err := manifest.save(dir); err != nil {
		return res, err
	}
	return res, nil
}

// ---- pools ----

func ensureFastPool(c *client, o *out) error {
	raw, err := c.do(http.MethodGet, "/admin/pools", nil)
	if err != nil {
		if isHTTP404(err) {
			fmt.Fprintln(o.w, "warning: controller has no pools API (older controller); skipping the fast pool")
			return nil
		}
		return err
	}
	var list ocPoolList
	if err := json.Unmarshal(raw, &list); err != nil {
		return err
	}
	for _, p := range list.Pools {
		if p.Name == ocFastPoolName {
			return nil
		}
	}
	pool := ocPool{Name: ocFastPoolName, Description: ocFastPoolDesc, Routing: "spread"}
	if _, err := c.do(http.MethodPut, "/admin/pools/"+ocFastPoolName, pool); err != nil {
		if isHTTP404(err) {
			fmt.Fprintln(o.w, "warning: controller has no pools API (older controller); skipping the fast pool")
			return nil
		}
		return err
	}
	fmt.Fprintln(o.w, "created pool fast (routing spread)")
	return nil
}

// ---- commands ----

func opencodeInit(c *client, o *out, args []string) error {
	fs := flag.NewFlagSet("opencode init", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	dir := fs.String("dir", ".", "project directory")
	provider := fs.String("provider", ocProviderDefault, "opencode provider id")
	baseURL := fs.String("base-url", "", "gateway base URL (default: controller URL + /v1)")
	force := fs.Bool("force", false, "replace an existing provider block in plain JSON")
	readTools := fs.Bool("read-tools", false, "allow read, grep and glob tools instead of none (~1k extra prompt tokens per call)")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("opencode init: %w", err)
	}
	if fs.NArg() != 0 {
		return errUsage
	}

	url := *baseURL
	if url == "" {
		url = c.base + "/v1"
	}

	if err := ensureFastPool(c, o); err != nil {
		return err
	}

	state, err := fetchClusterState(c)
	if err != nil {
		return err
	}

	block := buildProviderBlock(url, state.Models, state.Nodes)
	configPath, managed, err := opencodeWriteConfig(*dir, *provider, block, *force, o)
	if err != nil {
		return err
	}

	manifest := ocManifest{Version: 1, Provider: *provider, BaseURL: url, ReadTools: *readTools,
		ConfigPath: relPath(*dir, configPath), ConfigManaged: managed, Files: map[string]string{}}
	if managed {
		if data, err := os.ReadFile(configPath); err == nil {
			manifest.Files[manifest.ConfigPath] = sha256Hex(data)
		}
	}

	aliased := aliasedNodesFromModels(state.Models, state.Nodes)
	specs := managedAgentSpecs(*provider, *readTools, aliased)
	res, err := syncAgentFiles(*dir, specs, &manifest)
	if err != nil {
		return err
	}
	manifest.UpdatedAt = time.Now().UTC()
	if err := manifest.save(*dir); err != nil {
		return err
	}

	fmt.Fprintf(o.w, "agents: %s\n", res.summary())
	for _, w := range res.Warnings {
		fmt.Fprintln(o.w, "warning:", w)
	}
	if *readTools {
		fmt.Fprintln(o.w, "note:", ocReadToolsNoteWords)
	}
	return nil
}

func opencodeSync(c *client, o *out, args []string) error {
	fs := flag.NewFlagSet("opencode sync", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	dir := fs.String("dir", ".", "project directory")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("opencode sync: %w", err)
	}
	if fs.NArg() != 0 {
		return errUsage
	}
	res, err := runOpenCodeSync(c, *dir)
	if err != nil {
		return err
	}
	fmt.Fprintln(o.w, res.summary())
	for _, w := range res.Warnings {
		fmt.Fprintln(o.w, "warning:", w)
	}
	return nil
}

func opencodeWatch(c *client, o *out, args []string) error {
	fs := flag.NewFlagSet("opencode watch", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	dir := fs.String("dir", ".", "project directory")
	interval := fs.Duration("interval", 15*time.Second, "sync interval")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("opencode watch: %w", err)
	}
	if fs.NArg() != 0 {
		return errUsage
	}
	if *interval <= 0 {
		return fmt.Errorf("opencode watch: -interval must be positive")
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	tick := func() {
		res, err := runOpenCodeSync(c, *dir)
		ts := time.Now().Format(time.RFC3339)
		if err != nil {
			fmt.Fprintln(o.w, ts, "sync error:", err)
			return
		}
		if res.changed() || len(res.Warnings) > 0 {
			fmt.Fprintln(o.w, ts, res.summary())
			for _, w := range res.Warnings {
				fmt.Fprintln(o.w, "warning:", w)
			}
		}
	}
	tick()
	ticker := time.NewTicker(*interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return nil
		case <-ticker.C:
			tick()
		}
	}
}

func opencodeStatus(c *client, o *out, args []string) error {
	fs := flag.NewFlagSet("opencode status", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	dir := fs.String("dir", ".", "project directory")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("opencode status: %w", err)
	}
	if fs.NArg() != 0 {
		return errUsage
	}

	manifest, ok, err := loadManifest(*dir)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf("no %s; run 'pbctl opencode init' first", filepath.Join(*dir, ocManifestPath))
	}

	modelsRaw, err := c.request(http.MethodGet, "/v1/models", nil, c.apiKey)
	if err != nil {
		return err
	}
	var ml struct {
		Data []ocModel `json:"data"`
	}
	if err := json.Unmarshal(modelsRaw, &ml); err != nil {
		return err
	}
	byID := map[string]ocModel{}
	for _, m := range ml.Data {
		byID[m.ID] = m
	}

	names := manifest.agentNames()
	if len(names) == 0 {
		fmt.Fprintln(o.w, "no managed agents; run 'pbctl opencode init' or 'sync'")
	} else {
		var rows [][]string
		for _, name := range names {
			target := targetForAgentName(name)
			m, found := byID[target]
			served, nodesReady, status := "-", "0", "missing"
			if found {
				nodesReady = strconv.Itoa(m.Nodes)
				if m.Model != "" {
					served = m.Model
				}
				if m.Nodes > 0 {
					status = "ready"
				} else {
					status = "no nodes"
				}
			}
			rows = append(rows, []string{name, target, served, nodesReady, status})
		}
		o.table("NAME\tTARGET\tSERVED MODEL\tNODES READY\tSTATUS", rows)
	}
	fmt.Fprintf(o.w, "\nprovider %s, baseURL %s\n", manifest.Provider, manifest.BaseURL)
	return nil
}

func summarizePrewarmResults(results []ocPrewarmNodeResult) (ok, ms, errs string) {
	if len(results) == 0 {
		return "0/0", "-", ""
	}
	okCount, maxMS := 0, 0
	var errList []string
	for _, r := range results {
		if r.OK {
			okCount++
		}
		if r.MS > maxMS {
			maxMS = r.MS
		}
		if r.Error != "" {
			errList = append(errList, r.Error)
		}
	}
	return fmt.Sprintf("%d/%d", okCount, len(results)), strconv.Itoa(maxMS), strings.Join(errList, "; ")
}

func opencodePrewarm(c *client, o *out, args []string) error {
	fs := flag.NewFlagSet("opencode prewarm", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	dir := fs.String("dir", ".", "project directory")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("opencode prewarm: %w", err)
	}
	if fs.NArg() != 0 {
		return errUsage
	}

	manifest, ok, err := loadManifest(*dir)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf("no %s; run 'pbctl opencode init' first", filepath.Join(*dir, ocManifestPath))
	}

	names := manifest.agentNames()
	if len(names) == 0 {
		fmt.Fprintln(o.w, "no managed agents to prewarm")
		return nil
	}

	fmt.Fprintln(o.w, "note: opencode appends environment details to the system prompt, so prewarm mostly helps agents with long prompts or tools")
	var rows [][]string
	for _, name := range names {
		path := filepath.Join(*dir, ocAgentDirName, name+".md")
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		model, body, err := parseAgentFrontmatter(string(data))
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		target := strings.TrimPrefix(model, manifest.Provider+"/")
		req := ocPrewarmRequest{Target: target, Messages: []ocChatMessage{{Role: "system", Content: body}}}
		raw, err := c.do(http.MethodPost, "/admin/prewarm", req)
		if err != nil {
			rows = append(rows, []string{name, target, "-", "-", err.Error()})
			continue
		}
		var pr ocPrewarmResponse
		if err := json.Unmarshal(raw, &pr); err != nil {
			return err
		}
		okStr, ms, errs := summarizePrewarmResults(pr.Results)
		rows = append(rows, []string{name, target, okStr, ms, errs})
	}
	o.table("AGENT\tTARGET\tOK\tMS\tERROR", rows)
	return nil
}
